### ISSUE TITLE
Question about extrinsic

### ISSUE THREAD

**Issue by Gatsby23** [mitsurukato24/SimpleStereoVO#1]
Hi, it's a great job of simple stereo visual odometry. But there is a question about the extrinsic parameters in Camera.h. From comment, it seems the extrinsic for the stereo vo. But for kitti data ,how to get the extrinsic for this parameter？From the kitti calibration files, I can only get the parameters from calibration.txt like this:
![image](https://user-images.githubusercontent.com/18000675/113279181-656a6580-9315-11eb-9a38-f7e971bdac27.png)
How to set this two parameters？

**Comment by mitsurukato24** [comment]
I missed to attach the config file to run.  I have added kitti.yml so you can modify it to the directory where you saved the KITTI dataset and it will work correctly.
